import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import 'tailwindcss/tailwind.css'
import Arrow from "../../public/arrow.svg"
import Navigation from "../components/nav"
import Footer from "../components/footer"

export default function Home() {
  return (
    <div className="text-white bg-gray-900 grid gap-10">
      <Head>
        <title>Evon Capital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main className="flex justify-center items-center py-12 text-center">
        <div className="max-w-screen-md">

          <h1 className="text-6xl font-bold tracking-wide my-8 opacity-100">
            Ole omistaja, älä sijoittaja.
          </h1>


          <h2 className="my-3 text-lg opacity-80">
            Evon Capital on erittäin tuottohakuisten piensijoittajien yhteisyritys, joka sijoittaa varojaan pitkällä aikahorisontilla.
            Yhtiö yhdistää niin osakkaidensa varat kuin osaamisen — ja hakee markkinoihin nähden ylituottoa tällä synergialla.
          </h2>

          <h2 className="mt-8 text-lg opacity-80">
              Kiinnostaako lähteä mukaan? 👇
          </h2>

          <Link href="/waitlist" passHref>
            <a>
              <button className="
                bg-indigo-500 py-3 px-5 my-2 rounded-lg tracking-wider text-lg my-8 font-normal
                transition hover:bg-indigo-700 focus:ring group text-center
                "> 
                <span className="flex items-center">
                  Liity odotuslistalle
                  <Arrow className="transition transform group-hover:translate-x-1 "/>
                </span>
              </button>
            </a>
          </Link>

        </div>
      </main>

      <section className="flex justify-center">
        <div className="max-w-screen-md">
          <h3 className="text-indigo-500 tracking-wider text-lg my-3">
              Tietoa yrityksestä
          </h3>
          <h1 className="text-4xl font-bold tracking-wide mb-8">
              Evon Capital Oy
          </h1>
          <p className="text-lg opacity-80 my-5">
              Evon Capital on omia varojaan aktiivisesti sijoittava piensijoittajien yhteisyritys.
              Yhtiöllä ei varsinaisesti ole työntekijöitä, vaan osakkaat yhdessä vastaavat yhtiön liiketoiminnasta, sijoittamisesta ja markkinoinnista.
          </p>
        </div>
      </section>

      <Footer />

    </div>
  )
}
