import 'tailwindcss/tailwind.css'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Arrow from "../public/arrow.svg"

import Section from "@components/section"
import Title from "@components/title"
import Subtitle from "@components/subtitle"
import Prose from "@components/prose"

import Navigation from "@components/nav"
import Footer from "@components/footer"


export default function Home() {
  return (
    <div className="text-white bg-gray-900 grid gap-10 min-h-screen">
      <Head>
        <title>Evon Capital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main className="flex justify-center items-center text-center">
        <div className="max-w-screen-md">

          <h1 className="text-6xl font-bold tracking-wide my-8 opacity-100">
            Ole omistaja, älä sijoittaja.
          </h1>


          <h2 className="my-3 text-lg opacity-80">
            Evon Capital on erittäin tuottohakuisten piensijoittajien yhteisyritys, joka sijoittaa varojaan pitkällä aikahorisontilla.
            Yhtiö yhdistää niin osakkaidensa varat kuin osaamisen — ja hakee markkinoihin nähden ylituottoa tällä synergialla.
          </h2>

          <h2 className="mt-8 text-lg opacity-80">
              Kiinnostaako lähteä mukaan? 👇
          </h2>

          <Link href="/waitlist" passHref>
            <a>
              <button className="
                bg-indigo-500 py-3 px-5 my-2 rounded tracking-wider text-lg my-8 font-normal
                transition hover:bg-indigo-700 focus:ring group text-center
                "> 
                <span className="flex items-center">
                  Osallistu osakeantiin
                  <Arrow className="transition transform group-hover:translate-x-1 "/>
                </span>
              </button>
            </a>
          </Link>

        </div>
      </main>

      <Section>
          <Subtitle>
              Tietoa yrityksestä
          </Subtitle>
          <Title>
              Evon Capital
          </Title>
          <Prose large>
            Evon Capital on nuorten yrittäjien ja omistajien muodostama sijoitusyhtiö, joka tähtää 
            räväkkään sijoittamiseen, trendikkääseen näkyvyyteen ja ennen kaikkea verojen minimointiin. 
            Yhtiön osaava johto sekä joustava strategia ovat reseptimme ylituottoon vaihtuvissakin 
            markkinatilanteissa. 
          </Prose>
          <Prose large>
            Yhtiömme pyrkii myös perinteisen markkina-analyysin sekä sijoittamisen ohella tuottamaan omistajilleen lisäarvoa erilaisilla projekteilla, 
            joihin lukeutuu tämänhetkinen koneoppimis-projekti. 
            Sen tarkoituksena on pystyä lähitulevaisuudessa analysoimaan markkinoita tekoälyn avulla ja 
            reagoida tämän analyysin perusteella nopeasti osakkeiden markkina-arvojen heilahteluihin. 
            Tekoälyn on tarkoitus arvioida uutisten, Twitterin ja esimerkiksi onnettomuuksien vaikutuksia osakekurssiin nopeammin kuin ihminen pystyy tiedon käsittelemään.
          </Prose>
      </Section>

      <Section>
          <Subtitle>
            Mille pohjalle yhtiö on rakennettu?
          </Subtitle>
          <Title>
              Yhtiön arvot
          </Title>

          <div className="grid gap-10 justify-center">
            <span className="bg-gray-800 px-10 py-8 rounded shadow">
              <h3 className="text-xl font-bold tracking-wide">
                Eeppisyys (Legendaarisuus)
              </h3>
              <Prose>
                Kyseessä ei ole vain pelkkä yksinkertainen sijoitus tai joku helvetin Sirkka-tädin kahvila. 
                Meidän firmamme on kehittyvä legenda, jonka eeppisiä jakeita kirjoitetaan päivä päivältä. 
                Tavoitteemme on luoda sijoittajien yhteisö, 
                joka tunnetaan kansallisella tasolla sen räväkkyydestä ja hyvästä meiningistä.
                Emme pelkää tehdä, yrittää tai kertoa keitä me olemme. 
                Kävelemme ylpeästi kabinetista toiseen sikari suussa ja apina -logo paidassa.
              </Prose>
            </span>
            <span className="bg-gray-800 px-10 py-8 rounded shadow">
              <h3 className="text-xl font-bold tracking-wide">
                Tuloksellisuus
              </h3>
              <Prose>
                Kaiken keskiössä on juuri sinun osakkeiden arvon kasvattaminen. 
                Sijoitusten pitää tuottaa, taseen kasvaa ja osaamisen karttua. 
                Yritysjohto on sitoutunut minimoimaan aivan kaikki kulut kampaviinereistä omaan palkkaansa, 
                jota ei muuten makseta, jotta tulokset ovat mahdollisimman voitokkaat omistajilleen. 
                Kaikki hankkeet ja projektit, joihin yritys lähtee mukaan tai toteuttamaan, 
                on taustalla voitokkaan tuloksen hankkiminen.
              </Prose>
            </span>
            <span className="bg-gray-800 px-10 py-8 rounded shadow">
              <h3 className="text-xl font-bold tracking-wide">
                Omistajuus
              </h3>
              <Prose>
                Toimintamme tärkein arvo on omistajuus. 
                Jokainen osakkeita ostava henkilö saa myös automaattisesti tittelin Omistaja. 
                Tämä tarkoittaa useita erilaisia eksklusiivisia etuja ja työkaluja, 
                jotka saat käyttöösi, ja joita ei muiden yritysten osakkeita ostamalla saa. 
                Jokainen Omistaja on lähtökohtaisesti myös osakas ja jokaisella Omistajalla on mahdollisuus osallistua yrityksen operatiiviseen toimintaan, 
                mikäli intoa ja osaamista löytyy. 
                Omistajilla on mahdollisuus vaikuttaa yhtiön sijoituksiin esimerkiksi Financial Advisor Boardin kautta.
              </Prose>
            </span>
          </div>
      </Section>

      <Section>
          <Subtitle>
            Toimitusjohtajan tervehdys
          </Subtitle>
          <Title>
            Tervetuloa!
          </Title>
          <Prose large italic>
            Tervetuloa mukaan Evon Capitalin eeppiselle (legendaariselle) matkalle. 
            Olen tämän jahdin kippari sekä toimitusjohtaja Aatu Pulkkinen. 
            Tehtävänäni on pitää huolta, että kyseessä on tuottoisa, eeppinen (legendaarinen) ja kaikin puolin loistava risteily.
            Yhtiömme keskittyy jatkuvasti nostamaan osakkeen arvoa, mutta tavoitteenamme on myös huolehtia kunnollisesta riskienhallinnasta. 
            Vaikka yksittäiset positiomme voivat olla jopa erittäin riskialttiita, pyrimme salkun laajaan hajautukseen ja markkinoiden tarkkaan seurantaan. 
            Hienoa, että olet päätynyt jo sivuillemme, mutta toivottavasti voimme kohta kutsua sinuakin Omistajaksi ja juhlistaa tätä sikarien sekä viskilasillisen äärellä. 
            Antoisaa sijoittamista!
          </Prose>
          <Prose large italic>“To the fucking Moon!” 🚀🚀🚀</Prose>
          <p className="text-lg opacity-100 mt-5 max-w-prose text-right tracking-wider">Aatu Pulkkinen, toimitusjohtaja Evon Group</p>
      </Section>

      <Footer />

    </div>
  )
}
